sudo: required
dist: trusty
language: cpp

matrix:
  include:

    # Clang 4.0
    - env: COMPILER=clang++-4.0
      addons:
        apt:
          packages:
            - clang-4.0
            - g++-5
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0

    # Clang 5.0
    - env: COMPILER=clang++-5.0
      addons:
        apt:
          packages:
            - clang-5.0
            - g++-7
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0

    # Clang 6.0
    - env: COMPILER=clang++-6.0
      addons:
        apt:
          packages:
            - clang-6.0
            - g++-7
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0

    # Clang 7.0
    - env: COMPILER=clang++-7
      addons:
        apt:
          packages:
            - clang-7
            - g++-7
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-7 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

    # GCC 5
    - env: COMPILER=g++-5
      addons:
        apt:
          packages: g++-5
          sources:
            - ubuntu-toolchain-r-test

    # GCC 6
    - env: COMPILER=g++-6
      addons:
        apt:
          packages: g++-6
          sources:
            - ubuntu-toolchain-r-test

    # GCC 7
    - env: COMPILER=g++-7
      addons:
        apt:
          packages: g++-7
          sources:
            - ubuntu-toolchain-r-test

install:
    # Set the ${CXX} variable properly
    - export CXX=${COMPILER}
    - ${CXX} --version
    # Travis machines have 2 cores
    - JOBS=2
before_script:
    # have CMake generate build files
    - cd "${TRAVIS_BUILD_DIR}"
    - mkdir build && cd build
    - cmake ..
script:
    # build
    - cmake --build . -- -j${JOBS}
